### ISSUE TITLE
Error inspecting deployment

### ISSUE THREAD

**Issue by selfagency** [frencojobs/vscode-vercel#7]
When I click on a deployment

![image](https://user-images.githubusercontent.com/2541728/109761000-b32c6a80-7bbd-11eb-9b22-bb307c5c7028.png)

I get this error

![image](https://user-images.githubusercontent.com/2541728/109761007-b6275b00-7bbd-11eb-8545-09701f956e38.png)

**Comment by frencojobs** [comment]
Sorry for the delay, this ~will be~ is fixed by v1.0.3. Thank you very much for taking the time to file an issue. I really appreciate it.

**Comment by frencojobs** [comment]
Sorry for the delay, this will be fixed by v1.0.3. Thank you very much for taking the time to file an issue. I really appreciate it.
